# Docker Compose for running the multi-app Dapr setup defined in master.yaml
services:
  # Infra: Redis for pubsub/state used by ./components/*.yaml (redisHost: localhost:6379)
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - agent-flows
    restart: unless-stopped
    volumes:
      - redis-data:/data

  # Infra: Dapr placement service (required for workflows/actors)
  placement:
    image: daprio/dapr:1.16.0-rc.3
    command: ["./placement", "--port", "50005"]
    networks:
      - agent-flows
    restart: unless-stopped

  # Infra: Dapr scheduler service (required for workflows)
  scheduler:
    image: daprio/scheduler:1.16.0-rc.3
    command: ["./scheduler", "--port", "50007", "--etcd-data-dir", "/data"]
    networks:
      - agent-flows
    user: root
    restart: unless-stopped
    volumes:
    - "./dapr-etcd-data/:/data"

  # authenticator (services/ui/authenticator.py)
  authenticator:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    ports:
      - "5000:5000"
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5000"
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      MS_GRAPH_AUTHORITY: ${MS_GRAPH_AUTHORITY:-https://login.microsoftonline.com/consumers}
      MS_GRAPH_CLIENT_ID: ${MS_GRAPH_CLIENT_ID:-}
      MS_GRAPH_CLIENT_SECRET: ${MS_GRAPH_CLIENT_SECRET:-}
      PYTHONUNBUFFERED: "1"
      TOKEN_STATE_STORE_NAME: ${TOKEN_STATE_STORE_NAME:-tokenstatestore}
    command: ["python", "-m", "services.ui.authenticator"]
    restart: unless-stopped

  authenticator-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:authenticator"
    depends_on:
      - redis
      - placement
      - scheduler
    command: [
      "./daprd",
      "--app-id", "authenticator",
      "--app-port", "5000",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", " ",
      "--scheduler-host-address", " ",
      "--enable-metrics", "true",
      "--metrics-port", "9106",
      "--enable-profiling", "false"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

  # workflows publisher (services/workflow/worker.py)
  workflows:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
      - work:/.work
    environment:
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5001"
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      DEBUGPY_ENABLE: "0"
      LOCAL_VOICE_DOWNLOAD_FOLDER: "./.work/voice"
      ONEDRIVE_VOICE_ARCHIVE: ${ONEDRIVE_VOICE_ARCHIVE}
      ONEDRIVE_VOICE_INBOX: ${ONEDRIVE_VOICE_INBOX}
      ONEDRIVE_VOICE_POLL_INTERVAL: "60"
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      PYTHONUNBUFFERED: "1"
    command: ["python", "-m", "services.workflow.worker"]
    restart: unless-stopped

  workflows-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:workflows"
    depends_on:
      - placement
      - redis
      - scheduler
    command: [
      "./daprd",
      "--app-id", "workflows",
      "--app-port", "5001",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", "placement:50005",
      "--scheduler-host-address", "scheduler:50007", 
      "--enable-metrics", "true",
      "--metrics-port", "9100",
      "--enable-profiling", "false"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

  # worker-voice2action (services/workflow/worker_voice2action.py)
  worker-voice2action:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
      - work:/.work
    environment:
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5002"
      DAPR_INTENT_ORCHESTRATOR_TOPIC: "IntentOrchestrator"
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      DEBUGPY_ENABLE: "0"
      LOCAL_VOICE_DOWNLOAD_FOLDER: "./.work/voice"
      MS_GRAPH_AUTHORITY: ${MS_GRAPH_AUTHORITY:-https://login.microsoftonline.com/consumers}
      MS_GRAPH_CLIENT_ID: ${MS_GRAPH_CLIENT_ID}
      MS_GRAPH_CLIENT_SECRET: ${MS_GRAPH_CLIENT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      PYTHONUNBUFFERED: "1"
    command: ["python", "-m", "services.workflow.worker_voice2action"]
    restart: unless-stopped

  worker-voice2action-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:worker-voice2action"
    depends_on:
      - redis
      - placement
      - scheduler
    command: [
      "./daprd",
      "--app-id", "worker-voice2action",
      "--app-port", "5002",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", "placement:50005",
      "--scheduler-host-address", "scheduler:50007", 
      "--enable-metrics", "true",
      "--metrics-port", "9101",
      "--enable-profiling", "false"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

  # orchestrator-intent (services/intent_orchestrator/app.py)
  orchestrator-intent:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
      - work:/.work
    environment:
      DAPR_AGENTS_REGISTRY_STORE: agentstatestore
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5100"
      DAPR_BROADCAST_TOPIC: beacon_channel
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      DAPR_PUBSUB_NAME: pubsub
      DAPR_STATESTORE_NAME: workflowstatestore
      LOCAL_VOICE_DOWNLOAD_FOLDER: "./.work/voice"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYTHONUNBUFFERED: "1"
    command: ["python", "-m", "services.intent_orchestrator.app"]
    restart: unless-stopped

  orchestrator-intent-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:orchestrator-intent"
    depends_on:
      - redis
      - placement
      - scheduler
    command: [
      "./daprd",
      "--app-id", "orchestrator-intent",
      "--app-port", "5100",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", "placement:50005",
      "--scheduler-host-address", "scheduler:50007", 
      "--enable-metrics", "true",
      "--metrics-port", "9102",
      "--enable-profiling", "false"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

  # agent-taskplanner (services/intent_orchestrator/agent_tasker.py)
  agent-taskplanner:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
      - work:/.work
    environment:
      DAPR_AGENTS_REGISTRY_STORE: agentstatestore
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5101"
      DAPR_BROADCAST_TOPIC: beacon_channel
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      DAPR_PUBSUB_NAME: pubsub
      DAPR_STATESTORE_NAME: workflowstatestore
      DEBUGPY_ENABLE: "0"
      LOCAL_VOICE_DOWNLOAD_FOLDER: "./.work/voice"
      OFFICE_TIMEZONE: ${OFFICE_TIMEZONE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      PYTHONUNBUFFERED: "1"
    command: ["python", "-m", "services.intent_orchestrator.agent_tasker"]
    restart: unless-stopped

  agent-taskplanner-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:agent-taskplanner"
    depends_on:
      - redis
      - placement
      - scheduler
    command: [
      "./daprd",
      "--app-id", "agent-taskplanner",
      "--app-port", "5101",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", " ",
      "--scheduler-host-address", " ",
      "--enable-metrics", "true",
      "--metrics-port", "9103",
      "--enable-profiling", "false",
      "--log-as-json"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

  # agent-office-automation (services/intent_orchestrator/agent_office_automation.py)
  agent-office-automation:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
      - work:/.work
    environment:
      CREATE_TASK_WEBHOOK_URL: ${CREATE_TASK_WEBHOOK_URL}
      DAPR_AGENTS_REGISTRY_STORE: agentstatestore
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5102"
      DAPR_BROADCAST_TOPIC: beacon_channel
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      DAPR_PUBSUB_NAME: pubsub
      DAPR_STATESTORE_NAME: workflowstatestore
      DEBUGPY_ENABLE: "0"
      LOCAL_VOICE_DOWNLOAD_FOLDER: "./.work/voice"
      MS_GRAPH_AUTHORITY: ${MS_GRAPH_AUTHORITY:-https://login.microsoftonline.com/consumers}
      MS_GRAPH_CLIENT_ID: ${MS_GRAPH_CLIENT_ID}
      MS_GRAPH_CLIENT_SECRET: ${MS_GRAPH_CLIENT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      PYTHONUNBUFFERED: "1"
      SEND_MAIL_RECIPIENT: ${SEND_MAIL_RECIPIENT}
    command: ["python", "-m", "services.intent_orchestrator.agent_office_automation"]
    restart: unless-stopped

  agent-office-automation-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:agent-office-automation"
    depends_on:
      - redis
      - placement
      - scheduler
    command: [
      "./daprd",
      "--app-id", "agent-office-automation",
      "--app-port", "5102",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", " ",
      "--scheduler-host-address", " ",
      "--enable-metrics", "true",
      "--metrics-port", "9104",
      "--enable-profiling", "false",
      "--log-as-json"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

  # monitor (services/ui/monitor.py)
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.python-base
    image: dapr-agent-flow/python-base:local
    networks:
      - agent-flows
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DAPR_AGENTS_STATE_DIR: "./.dapr_state"
      DAPR_APP_PORT: "5199"
      DAPR_BROADCAST_TOPIC: beacon_channel
      DAPR_LOG_LEVEL: ${DAPR_LOG_LEVEL:-warn}
      DAPR_PUBSUB_NAME: pubsub
      DEBUGPY_ENABLE: "0"
      LOCAL_VOICE_DOWNLOAD_FOLDER: "./.work/voice"
      PYDEVD_DISABLE_FILE_VALIDATION: "1"
      PYTHONUNBUFFERED: "1"
    command: ["python", "-m", "services.ui.monitor"]
    restart: unless-stopped

  monitor-dapr:
    image: daprio/daprd:1.16.0-rc.3
    network_mode: "service:monitor"
    depends_on:
      - redis
      - placement
      - scheduler
    command: [
      "./daprd",
      "--app-id", "monitor",
      "--app-port", "5199",
      "--log-level", "${DAPR_LOG_LEVEL:-warn}",
      "--config", "/app/docker-components/dapr-config.yaml",
      "--resources-path", "/app/docker-components",
      "--placement-host-address", " ",
      "--scheduler-host-address", " ",
      "--enable-metrics", "true",
      "--metrics-port", "9105",
      "--enable-profiling", "false"
    ]
    volumes:
      - ./:/app
    restart: unless-stopped

volumes:
  redis-data: {}
  dapr-etcd-data: {}
  work: {}

networks:
  agent-flows: null