apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: agentstatestore
spec:
  type: state.sqlite
  version: v1
  metadata:
  - name: connectionString
    value: "./.data/agentstatestore.db"
  - name: keyPrefix
    value: none
scopes:
- orchestrator-intent
- agent-taskplanner
- agent-office-automation