apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: memorystatestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
scopes:
- agent-facilitator
- agent-office-automation