apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflowstatestore
spec:
  type: state.sqlite
  version: v1
  metadata:
  - name: connectionString
    value: "./.data/workflowstatestore.db"
  - name: actorStateStore
    value: "true"
scopes:
- worker-voice2action
- orchestrator-intent
- agent-task-planner
- agent-office-automation