apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: voice2action-schedule-sub
spec:
  topic: voice2action-schedule
  route: /schedule-voice2action
  pubsubname: pubsub
scopes:
- worker-voice2action
