apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: agentstatestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: none
scopes:
- orchestrator-intent
- agent-taskplanner
- agent-office-automation