apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: envvar-secret-store
spec:
  type: secretstores.local.env
  version: v1
scopes:
  - authenticator
  - workflows
  - worker-voice2action
  - orchestrator-intent
  - agent-task-planner
  - agent-office-automation
  - web-monitor
